# -*- coding: utf-8 -*-
"""app2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_-undB6nYDcmAtPlmZoIGg22vJ_mYQA
"""

import streamlit as st
from github import Github
import json

# --- Configuration ---
# Store these in Streamlit Secrets for security!
GITHUB_TOKEN = st.secrets["GITHUB_TOKEN"]
REPO_NAME = "your-username/streamlit-bank"
FILE_PATH = "ledger.json"

g = Github(GITHUB_TOKEN)
repo = g.get_repo(REPO_NAME)

def get_ledger():
    file_content = repo.get_contents(FILE_PATH)
    data = json.loads(file_content.decoded_content.decode())
    return data, file_content.sha

def update_ledger(new_data, sha):
    content = json.dumps(new_data, indent=4)
    repo.update_file(FILE_PATH, "Update balance", content, sha)

# --- Streamlit UI ---
st.title("💸 Mini-Pay: GitHub Edition")

ledger, sha = get_ledger()

# Display Balances
st.subheader("Current Balances")
st.table(ledger)

# Transaction Form
with st.form("transfer_form"):
    sender = st.selectbox("From", list(ledger.keys()))
    recipient = st.selectbox("To", [name for name in ledger.keys() if name != sender])
    amount = st.number_input("Amount", min_value=1, step=10)
    submit = st.form_submit_button("Send Money")

if submit:
    if ledger[sender] >= amount:
        # Perform Transfer
        ledger[sender] -= amount
        ledger[recipient] += amount

        # Save to GitHub
        update_ledger(ledger, sha)
        st.success(f"Successfully sent ${amount} to {recipient}!")
        st.balloons()
    else:
        st.error("Insufficient funds!")