# -*- coding: utf-8 -*-
"""app2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_-undB6nYDcmAtPlmZoIGg22vJ_mYQA
"""

import streamlit as st
from github import Github
import json

# --- 1. Configuration & Connection ---
# Make sure GITHUB_TOKEN is in your Streamlit Cloud Secrets!
GITHUB_TOKEN = st.secrets["GITHUB_TOKEN"]
REPO_NAME = "aelfakir/streamlit-bank" 
FILE_PATH = "ledger.json"

# Initialize GitHub connection
g = Github(GITHUB_TOKEN)
repo = g.get_repo(REPO_NAME)

def get_ledger():
    """Fetches the current ledger and its unique SHA ID from GitHub."""
    file_content = repo.get_contents(FILE_PATH)
    data = json.loads(file_content.decoded_content.decode())
    return data, file_content.sha

def update_ledger(new_data, sha):
    """Uploads the updated dictionary back to GitHub."""
    content = json.dumps(new_data, indent=4)
    repo.update_file(FILE_PATH, "Transaction Update", content, sha)

# --- 2. Streamlit User Interface ---
st.set_page_config(page_title="GitHub Mini-Pay", page_icon="💸")
st.title("💸 Mini-Pay: GitHub Edition")

# Fetch data at the start of every run
try:
    ledger, sha = get_ledger()
except Exception as e:
    st.error(f"Could not connect to GitHub: {e}")
    st.stop()

# Display Current Balances
st.subheader("Bank Ledger")
# Using columns to make the table look cleaner
cols = st.columns(len(ledger))
for i, (name, balance) in enumerate(ledger.items()):
    cols[i].metric(label=name, value=f"${balance}")

st.divider()

# --- 3. Transaction Form ---
st.subheader("Send a Payment")
with st.form("transfer_form", clear_on_submit=True):
    sender = st.selectbox("From", list(ledger.keys()))
    # Filter recipient list so you can't send money to yourself
    recipient_options = [name for name in ledger.keys() if name != sender]
    recipient = st.selectbox("To", recipient_options)
    
    amount = st.number_input("Amount ($)", min_value=1, max_value=max(ledger.values()), step=10)
    submit = st.form_submit_button("Confirm Transfer")

# --- 4. Logic Execution ---
if submit:
    if ledger[sender] >= amount:
        with st.spinner("Processing transaction on GitHub..."):
            # Update local data
            ledger[sender] -= amount
            ledger[recipient] += amount

            try:
                # Push to GitHub
                update_ledger(ledger, sha)
                
                # Feedback to user
                st.success(f"Successfully transferred ${amount} from {sender} to {recipient}!")
                st.balloons()
                
                # CRUCIAL: Rerun the app so the table shows the new values immediately
                st.rerun()
                
            except Exception as e:
                st.error(f"Transaction failed during GitHub upload: {e}")
    else:
        st.error(f"Insufficient funds! {sender} only has ${ledger[sender]}.")

# Optional: Add a footer
st.caption("Powered by Streamlit and GitHub API")
